// <auto-generated />
using Infastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241230104746_db1")]
    partial class db1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("Calories100g")
                        .HasColumnType("real");

                    b.Property<float?>("CaloriesPerMeal")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FoodCodes")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FoodWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MealCarbs100g")
                        .HasColumnType("real");

                    b.Property<float?>("MealCarbsPerMeal")
                        .HasColumnType("real");

                    b.Property<float?>("MealFats100g")
                        .HasColumnType("real");

                    b.Property<float?>("MealFatsPerMeal")
                        .HasColumnType("real");

                    b.Property<float?>("MealProtein100g")
                        .HasColumnType("real");

                    b.Property<float?>("MealProteinPerMeal")
                        .HasColumnType("real");

                    b.Property<int?>("MealTotalWeight")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("MealEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
